"""Tools available to the CodeGenAgent."""

from __future__ import annotations

import json
import ast


def validate_python(code: str) -> str:
    """Parse Python code and check for syntax errors.

    Args:
        code: Python source code to validate.

    Returns:
        JSON string with validation result.
    """
    try:
        ast.parse(code)
        return json.dumps({"tool": "validate_python", "valid": True, "errors": []})
    except SyntaxError as e:
        return json.dumps(
            {
                "tool": "validate_python",
                "valid": False,
                "errors": [{"line": e.lineno, "message": str(e.msg)}],
            }
        )


def generate_tests(code: str, language: str = "python") -> str:
    """Generate unit test stubs for a piece of code.

    Args:
        code: Source code to generate tests for.
        language: The programming language.

    Returns:
        JSON string with test suggestions.
    """
    return json.dumps(
        {
            "tool": "generate_tests",
            "language": language,
            "suggestion": (
                f"# Test stubs for the provided {language} code\n"
                "# In production, the LLM would generate comprehensive tests.\n"
                f"# Code length: {len(code)} characters"
            ),
        }
    )


def explain_code(code: str) -> str:
    """Produce a line-by-line explanation of code.

    Args:
        code: Source code to explain.

    Returns:
        JSON explanation string.
    """
    lines = code.strip().split("\n")
    return json.dumps(
        {
            "tool": "explain_code",
            "total_lines": len(lines),
            "explanation": f"This code has {len(lines)} lines. A detailed explanation would be generated by the LLM.",
        }
    )


CODEGEN_TOOLS = [
    {
        "name": "validate_python",
        "description": "Validate Python code for syntax errors",
        "input_schema": {
            "type": "object",
            "properties": {"code": {"type": "string", "description": "Python source code"}},
            "required": ["code"],
        },
    },
    {
        "name": "generate_tests",
        "description": "Generate unit test stubs for given code",
        "input_schema": {
            "type": "object",
            "properties": {
                "code": {"type": "string", "description": "Source code"},
                "language": {"type": "string", "description": "Language", "default": "python"},
            },
            "required": ["code"],
        },
    },
    {
        "name": "explain_code",
        "description": "Produce a line-by-line explanation of code",
        "input_schema": {
            "type": "object",
            "properties": {"code": {"type": "string", "description": "Source code to explain"}},
            "required": ["code"],
        },
    },
]

TOOL_DISPATCH = {
    "validate_python": lambda args: validate_python(args["code"]),
    "generate_tests": lambda args: generate_tests(args["code"], args.get("language", "python")),
    "explain_code": lambda args: explain_code(args["code"]),
}
